import React, { useState, useEffect, useMemo } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { useApp } from '../components/AppContext';
import { useAuth } from '@/lib/AuthContext';
import ManageUsersSection from '../components/settings/ManageUsersSection';
import AutoAssignSettings from '../components/settings/AutoAssignSettings';
import RestrictedAssignSettings from '../components/settings/RestrictedAssignSettings';
import GoogleCalendarSettings from '../components/settings/GoogleCalendarSettings';
import SlackGamesSettings from '../components/settings/SlackGamesSettings';
import RigCheckUsersSettings from '../components/settings/RigCheckUsersSettings';
import RigCheckSlackSettings from '../components/settings/RigCheckSlackSettings';
import AnalyticsGoogleSync from '../components/settings/AnalyticsGoogleSync';
import EnablePushCard from '../components/notifications/EnablePushCard';
import DataImportSection from '../components/settings/DataImportSection';
import SettingsCategory from '../components/settings/SettingsCategory';
import { resolveAppLogoUrl } from '../components/brand/BrandMark';
import { pickSetting, pickSettingValue } from '../utils/appSettings';
import { THEME_DEFAULTS, applyTheme, isHexColor, normalizeHexColor, parseTheme } from '../utils/theme';
import FilePickerButton from '../components/common/FilePickerButton';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import {
  User, RefreshCw, MessageSquare, Save, Image, DollarSign, Bell, KeyRound,
  CalendarDays, Database, Users, Globe, Palette
} from 'lucide-react';
import ChangePasswordForm from '../components/auth/ChangePasswordForm';
import { useTimezone } from '@/components/TimezoneContext';
import { TIMEZONE_OPTIONS, deviceTimeZone, formatTimezoneAbbr } from '@/utils/timezone';
import { DEFAULT_INVOICE_EXPORT_NAME, INVOICE_EXPORT_NAME_KEY, invoiceExportName } from '@/utils/invoiceExport';

function MessageTemplatesSection({ appSettings, queryClient }) {
  const defaultRigs = 'Rigs ready for today: {list}';
  const defaultOk = '{name} complete, no issues to report.';
  const defaultIssues = '{name} complete — ⚠️ Issues reported: {notes}';

  const [rigsTemplate, setRigsTemplate] = React.useState('');
  const [summaryOk, setSummaryOk] = React.useState('');
  const [summaryIssues, setSummaryIssues] = React.useState('');
  const [saved, setSaved] = React.useState(false);

  React.useEffect(() => {
    if (!appSettings.length) return;
    setRigsTemplate(appSettings.find(s => s.key === 'rigscheck_template')?.value || defaultRigs);
    setSummaryOk(appSettings.find(s => s.key === 'summary_template_ok')?.value || defaultOk);
    setSummaryIssues(appSettings.find(s => s.key === 'summary_template_issues')?.value || defaultIssues);
  }, [appSettings]);

  const handleSave = async () => {
    const pairs = [
      { key: 'rigscheck_template', value: rigsTemplate, description: 'Rigs check message template' },
      { key: 'summary_template_ok', value: summaryOk, description: 'Shoot summary — no issues template' },
      { key: 'summary_template_issues', value: summaryIssues, description: 'Shoot summary — issues template' },
    ];
    for (const pair of pairs) {
      const existing = appSettings.find(s => s.key === pair.key);
      if (existing) {
        await base44.entities.AppSettings.update(existing.id, { value: pair.value });
      } else {
        await base44.entities.AppSettings.create(pair);
      }
    }
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
    queryClient.invalidateQueries({ queryKey: ['appSettings'] });
  };

  return (
    <Card className="bg-slate-900 border-slate-800 mb-6">
      <CardHeader className="border-b border-slate-800 pb-4">
        <CardTitle className="text-slate-100 flex items-center gap-2">
          <MessageSquare className="h-5 w-5 text-orange-400" /> Message Templates
        </CardTitle>
      </CardHeader>
      <CardContent className="pt-4 space-y-4">
        <p className="text-xs text-slate-500">
          Customise the messages generated by the Rigs Check and Shoot Summary panels.
        </p>

        <div>
          <label className="text-xs text-slate-400 block mb-1">
            Rigs Check message — use <code className="text-orange-400">{'{list}'}</code> for the shoot list
          </label>
          <Input
            value={rigsTemplate}
            onChange={e => setRigsTemplate(e.target.value)}
            placeholder={defaultRigs}
            className="bg-slate-800 border-slate-800 text-slate-100 placeholder:text-gray-600 text-sm"
          />
          <p className="text-xs text-gray-600 mt-1">
            Example output: <span className="text-slate-400 italic">Rigs ready for today: Nationals (Data/Fancam), Lightning (Data/Fancam/Sound)</span>
          </p>
        </div>

        <div>
          <label className="text-xs text-slate-400 block mb-1">
            Shoot Summary — no issues — use <code className="text-orange-400">{'{name}'}</code> for shoot name
          </label>
          <Input
            value={summaryOk}
            onChange={e => setSummaryOk(e.target.value)}
            placeholder={defaultOk}
            className="bg-slate-800 border-slate-800 text-slate-100 placeholder:text-gray-600 text-sm"
          />
        </div>

        <div>
          <label className="text-xs text-slate-400 block mb-1">
            Shoot Summary — issues reported — use <code className="text-orange-400">{'{name}'}</code> and <code className="text-orange-400">{'{notes}'}</code>
          </label>
          <Input
            value={summaryIssues}
            onChange={e => setSummaryIssues(e.target.value)}
            placeholder={defaultIssues}
            className="bg-slate-800 border-slate-800 text-slate-100 placeholder:text-gray-600 text-sm"
          />
        </div>

        <Button onClick={handleSave} className="bg-orange-500 hover:bg-orange-400 gap-2">
          <Save className="h-4 w-4" /> {saved ? '✓ Saved!' : 'Save Templates'}
        </Button>
      </CardContent>
    </Card>
  );
}

const APP_LOGO_ACCEPT = 'image/png,image/jpeg,image/webp,image/gif,image/svg+xml,image/x-icon,image/vnd.microsoft.icon,.png,.jpg,.jpeg,.webp,.gif,.svg,.ico';
const APP_LOGO_TYPES = new Set([
  'image/png', 'image/jpeg', 'image/webp', 'image/gif',
  'image/svg+xml', 'image/x-icon', 'image/vnd.microsoft.icon', 'image/bmp',
]);

function isHeicFile(file) {
  const type = String(file?.type || '').toLowerCase();
  const name = String(file?.name || '').toLowerCase();
  return type.includes('heic') || type.includes('heif') || /\.hei[cf]$/i.test(name);
}

function isAllowedLogoFile(file) {
  if (isHeicFile(file)) return false;
  if (file?.type && APP_LOGO_TYPES.has(file.type)) return true;
  return /\.(png|jpe?g|webp|gif|svg|ico|bmp)$/i.test(file?.name || '');
}

function AppLogoControls({ logoUrl, uploading, error, onUpload, onClear }) {
  return (
    <div className="flex items-center gap-4 flex-wrap">
      <div className="w-16 h-16 bg-slate-800 rounded-xl flex items-center justify-center overflow-hidden border border-slate-800">
        <img src={resolveAppLogoUrl(logoUrl)} alt="App icon" className="w-full h-full object-contain" />
      </div>
      <div className="min-w-0 flex-1">
        <p className="text-sm font-medium text-slate-200">App icon</p>
        <p className="text-sm text-slate-400 mb-2">
          Used on sign-in, in the sidebar, the browser tab, and when someone installs the app. PNG, JPEG, WebP, GIF, SVG, or ICO.
        </p>
        <div className="flex flex-wrap gap-2">
          <FilePickerButton
            id="app-logo-file"
            accept={`image/*,${APP_LOGO_ACCEPT}`}
            disabled={uploading}
            onChange={onUpload}
          >
            <Image className="h-4 w-4" />
            {uploading ? 'Uploading...' : logoUrl ? 'Replace icon' : 'Upload icon'}
          </FilePickerButton>
          {logoUrl && (
            <Button type="button" size="sm" variant="outline" onClick={onClear}
              className="border-slate-700 text-slate-300 hover:bg-slate-800">
              Use default
            </Button>
          )}
        </div>
        {error ? <p className="text-xs text-red-400 mt-2">{error}</p> : null}
      </div>
    </div>
  );
}

function ThemeColorField({ label, hint, value, fallback, onChange }) {
  const pickerValue = isHexColor(value) ? normalizeHexColor(value) : fallback;
  return (
    <label className="block min-w-[11rem] flex-1">
      <span className="text-xs text-slate-400 block mb-1">{label}</span>
      <div className="flex items-center gap-2">
        <input
          type="color"
          value={pickerValue}
          onChange={(e) => onChange(e.target.value)}
          className="h-9 w-12 cursor-pointer rounded border border-slate-700 bg-slate-800 p-0.5"
        />
        <Input
          value={value}
          onChange={(e) => onChange(e.target.value)}
          className="bg-slate-800 border-slate-700 text-slate-100 text-sm font-mono uppercase"
        />
      </div>
      {hint ? <p className="text-xs text-slate-500 mt-1">{hint}</p> : null}
    </label>
  );
}

function AppearanceThemeControls({ appSettings, logoUrl, splashUrl, onSave }) {
  const savedTheme = parseTheme({
    theme_canvas: pickSettingValue(appSettings, 'theme_canvas'),
    theme_surface: pickSettingValue(appSettings, 'theme_surface'),
    theme_accent: pickSettingValue(appSettings, 'theme_accent'),
    theme_line: pickSettingValue(appSettings, 'theme_line'),
    app_logo_url: logoUrl,
    splash_image_url: splashUrl,
  });
  const [draft, setDraft] = React.useState(savedTheme);
  const [saving, setSaving] = React.useState(false);
  const [saved, setSaved] = React.useState(false);

  React.useEffect(() => {
    setDraft((prev) => ({
      ...prev,
      canvas: savedTheme.canvas,
      surface: savedTheme.surface,
      accent: savedTheme.accent,
      line: savedTheme.line,
      logo: savedTheme.logo,
      splash: savedTheme.splash,
    }));
  }, [savedTheme.canvas, savedTheme.surface, savedTheme.accent, savedTheme.line, savedTheme.logo, savedTheme.splash]);

  const updateField = (key, value) => {
    const next = { ...draft, [key]: value, logo: logoUrl, splash: splashUrl };
    setDraft(next);
    applyTheme(next);
  };

  const persist = async (theme) => {
    setSaving(true);
    try {
      await onSave({
        canvas: normalizeHexColor(theme.canvas, THEME_DEFAULTS.canvas),
        surface: normalizeHexColor(theme.surface, THEME_DEFAULTS.surface),
        accent: normalizeHexColor(theme.accent, THEME_DEFAULTS.accent),
        line: normalizeHexColor(theme.line, THEME_DEFAULTS.line),
      });
      applyTheme({ ...theme, logo: logoUrl, splash: splashUrl });
      setSaved(true);
      setTimeout(() => setSaved(false), 2000);
    } finally {
      setSaving(false);
    }
  };

  return (
    <Card className="bg-slate-900 border-slate-800 mt-4">
      <CardHeader className="border-b border-slate-800 pb-4">
        <CardTitle className="text-slate-100 flex items-center gap-2">
          <Palette className="h-5 w-5 text-orange-400" /> Colours
        </CardTitle>
      </CardHeader>
      <CardContent className="pt-4 space-y-4">
        <p className="text-sm text-slate-400">
          These colours apply to the load screen, page background, dashboard cards, and borders. Changes preview immediately; save to keep them for everyone.
        </p>
        <div className="flex flex-wrap gap-4">
          <ThemeColorField
            label="Page background"
            hint="Load screen and app canvas"
            value={draft.canvas}
            fallback={THEME_DEFAULTS.canvas}
            onChange={(value) => updateField('canvas', value)}
          />
          <ThemeColorField
            label="Card colour"
            hint="Dashboard cards and panels"
            value={draft.surface}
            fallback={THEME_DEFAULTS.surface}
            onChange={(value) => updateField('surface', value)}
          />
          <ThemeColorField
            label="Accent"
            hint="Buttons and highlights"
            value={draft.accent}
            fallback={THEME_DEFAULTS.accent}
            onChange={(value) => updateField('accent', value)}
          />
          <ThemeColorField
            label="Card borders"
            hint="Outline around dashboard cards"
            value={draft.line}
            fallback={THEME_DEFAULTS.line}
            onChange={(value) => updateField('line', value)}
          />
        </div>
        <div className="flex flex-wrap gap-2">
          <Button
            type="button"
            disabled={saving}
            onClick={() => persist(draft)}
            className="bg-orange-500 hover:bg-orange-400 gap-2"
          >
            <Save className="h-4 w-4" /> {saved ? 'Saved' : saving ? 'Saving...' : 'Save colours'}
          </Button>
          <Button
            type="button"
            variant="outline"
            disabled={saving}
            onClick={() => {
              const next = { ...THEME_DEFAULTS, logo: logoUrl, splash: splashUrl };
              setDraft(next);
              applyTheme(next);
              persist(next);
            }}
            className="border-slate-700 text-slate-300 hover:bg-slate-800"
          >
            Reset defaults
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

// App Version bump — triggers RefreshReminder for all users
function AppVersionBump({ appSettings, queryClient }) {
  const [bumping, setBumping] = React.useState(false);
  const [done, setDone] = React.useState(false);

  const handleBump = async () => {
    setBumping(true);
    const newVersion = Date.now().toString();
    const existing = appSettings.find(s => s.key === 'app_version');
    if (existing) {
      await base44.entities.AppSettings.update(existing.id, { value: newVersion });
    } else {
      await base44.entities.AppSettings.create({ key: 'app_version', value: newVersion, description: 'App version — bump to notify users to refresh' });
    }
    setBumping(false);
    setDone(true);
    setTimeout(() => setDone(false), 3000);
    queryClient.invalidateQueries({ queryKey: ['appSettings'] });
  };

  return (
    <div className="border-t border-slate-800 pt-4 mt-2">
      <p className="text-xs text-slate-500 mb-2">Notify all users to refresh the app (e.g. after a major update):</p>
      <Button size="sm" onClick={handleBump} disabled={bumping}
        className="bg-orange-700 hover:bg-orange-600 gap-2 text-sm">
        <RefreshCw className="h-4 w-4" />
        {done ? '✓ Notification sent!' : bumping ? 'Sending...' : 'Send Refresh Reminder to All Users'}
      </Button>
    </div>
  );
}

const SLACK_PHASES = [
  { key: 'setup_complete', label: 'Setup Complete', placeholder: 'Setup complete — {team} shoot ready to go!' },
  { key: 'pre_shoot_started', label: 'Pre-Shoot Started', placeholder: 'Pre-shoot started — {team}' },
  { key: 'attention_started', label: 'Attention Started', placeholder: 'Attention phase started — {team}' },
  { key: 'sound_started', label: 'Sound Started', placeholder: 'Sound check in progress — {team}' },
];

function ChangePasswordCard() {
  const queryClient = useQueryClient();
  const [saved, setSaved] = useState(false);

  return (
    <div>
      <ChangePasswordForm
        requireCurrent
        submitLabel={saved ? 'Password updated' : 'Update password'}
        inputClassName="bg-slate-800 border-slate-800 text-slate-100 placeholder:text-gray-600 text-sm w-full rounded-md px-3 py-2 border"
        buttonClassName="inline-flex items-center justify-center rounded-md bg-orange-500 hover:bg-orange-400 disabled:opacity-60 text-white text-sm font-medium px-4 py-2"
        errorClassName="rounded-md border border-red-800/80 bg-red-950/40 text-red-400 text-sm px-3 py-2"
        onSuccess={() => {
          queryClient.invalidateQueries({ queryKey: ['currentUser'] });
          setSaved(true);
          setTimeout(() => setSaved(false), 2500);
        }}
      />
    </div>
  );
}

function InvoiceExportNameCard({ appSettings, queryClient }) {
  const [name, setName] = React.useState(DEFAULT_INVOICE_EXPORT_NAME);
  const [saved, setSaved] = React.useState(false);

  React.useEffect(() => {
    setName(invoiceExportName(appSettings));
  }, [appSettings]);

  const handleSave = async () => {
    const value = name.trim() || DEFAULT_INVOICE_EXPORT_NAME;
    const existing = appSettings.find((item) => item.key === INVOICE_EXPORT_NAME_KEY);
    if (existing) {
      await base44.entities.AppSettings.update(existing.id, { value });
    } else {
      await base44.entities.AppSettings.create({
        key: INVOICE_EXPORT_NAME_KEY,
        value,
        description: 'Accounts invoice CSV export name',
      });
    }
    setName(value);
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
    queryClient.invalidateQueries({ queryKey: ['appSettings'] });
  };

  return (
    <Card className="bg-slate-900 border-slate-800 mb-6">
      <CardHeader className="border-b border-slate-800 pb-4">
        <CardTitle className="text-slate-100 flex items-center gap-2">
          <DollarSign className="h-5 w-5 text-emerald-400" /> Invoice export
        </CardTitle>
      </CardHeader>
      <CardContent className="pt-4 space-y-3">
        <p className="text-xs text-slate-500">
          This name is used for the Accounts CSV download. Default is Remote Photography Invoice.
        </p>
        <Input
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder={DEFAULT_INVOICE_EXPORT_NAME}
          className="bg-slate-800 border-slate-800 text-slate-100 placeholder:text-gray-600 text-sm max-w-md"
        />
        <Button onClick={handleSave} className="bg-orange-500 hover:bg-orange-400 gap-2">
          <Save className="h-4 w-4" /> {saved ? 'Saved' : 'Save invoice name'}
        </Button>
      </CardContent>
    </Card>
  );
}

export default function Settings() {
  const { user, isAdmin, isAnalytics, isAccounts } = useApp();
  const { refreshPublicSettings } = useAuth();
  const { storedTimezone, setTimezone, timeZone, abbr } = useTimezone();
  const [timezoneSaved, setTimezoneSaved] = useState(false);
  const [now, setNow] = useState(new Date());
  const queryClient = useQueryClient();

  const [slackMsgs, setSlackMsgs] = useState({});
  const [slackSaved, setSlackSaved] = useState(false);
  const [rateBaseInput, setRateBaseInput] = useState('');
  const [adminDayHoursInput, setAdminDayHoursInput] = useState('9.5');
  const [rateAdditionalInput, setRateAdditionalInput] = useState('');
  const [ratePostponedInput, setRatePostponedInput] = useState('250');
  const [rateStandbyInput, setRateStandbyInput] = useState('500');
  const [ratesSaved, setRatesSaved] = useState(false);

  // Logo
  const [logoUploading, setLogoUploading] = useState(false);
  const [logoError, setLogoError] = useState('');
  const [bgUploading, setBgUploading] = useState(false);
  const [bgError, setBgError] = useState('');
  const [splashUploading, setSplashUploading] = useState(false);
  const [splashError, setSplashError] = useState('');

  const { data: appSettings = [] } = useQuery({
    queryKey: ['appSettings'],
    queryFn: () => base44.entities.AppSettings.list(),
  });

  const { data: rawUsers = [] } = useQuery({
    queryKey: ['allUsers'],
    queryFn: () => base44.entities.User.list(),
    enabled: isAdmin,
  });

  const { data: pendingUsers = [] } = useQuery({
    queryKey: ['pendingUsers'],
    queryFn: () => base44.entities.PendingUser.list(),
    enabled: isAdmin,
  });

  // Merge PendingUser (admin-defined names/roles) with User entity records
  const allUsers = useMemo(() => {
    const map = new Map();
    pendingUsers.forEach(pu => {
      const email = pu.email?.trim().toLowerCase();
      if (!email) return;
      map.set(email, { email, full_name: pu.full_name || '', role: pu.role || 'user', inactive: pu.inactive || false });
    });
    rawUsers.forEach(u => {
      const email = u.email?.trim().toLowerCase();
      if (!email) return;
      const existing = map.get(email);
      // Login role on User is the source of truth; PendingUser only fills missing name.
      map.set(email, {
        ...u,
        email,
        full_name: existing?.full_name || u.full_name || '',
        role: u.role || existing?.role || 'user',
        inactive: u.inactive || existing?.inactive || false,
      });
    });
    return Array.from(map.values());
  }, [rawUsers, pendingUsers]);



  const logoSetting = pickSetting(appSettings, 'app_logo_url');
  const logoUrl = logoSetting?.value;
  const loginBgSetting = pickSetting(appSettings, 'login_background_url');
  const loginBgUrl = loginBgSetting?.value;
  const splashSetting = pickSetting(appSettings, 'splash_image_url');
  const splashUrl = splashSetting?.value;

  useEffect(() => {
    const iv = setInterval(() => setNow(new Date()), 1000);
    return () => clearInterval(iv);
  }, []);

  useEffect(() => {
    if (!appSettings.length) return;
    const msgs = {};
    SLACK_PHASES.forEach(p => {
      const setting = appSettings.find(s => s.key === `slack_${p.key}`);
      if (setting) msgs[p.key] = setting.value;
    });
    setSlackMsgs(msgs);
    const br = appSettings.find(s => s.key === 'base_rate')?.value;
    const ar = appSettings.find(s => s.key === 'additional_rate')?.value;
    const pr = appSettings.find(s => s.key === 'postponed_rate')?.value;
    if (br) setRateBaseInput(br);
    if (ar) setRateAdditionalInput(ar);
    if (pr) setRatePostponedInput(pr);
    const sr = appSettings.find(s => s.key === 'standby_rate')?.value;
    if (sr) setRateStandbyInput(sr);
    const adh = appSettings.find(s => s.key === 'admin_day_hours')?.value;
    if (adh) setAdminDayHoursInput(adh);
  }, [appSettings]);

  const handleSaveRates = async () => {
    const pairs = [
      { key: 'base_rate', value: rateBaseInput || '1000', description: 'Standard shoot rate (ZAR)' },
      { key: 'additional_rate', value: rateAdditionalInput || '250', description: 'Additional shoot rate (ZAR)' },
      { key: 'postponed_rate', value: ratePostponedInput || '250', description: 'Postponed shoot fee (ZAR)' },
      { key: 'standby_rate', value: rateStandbyInput || '500', description: 'Operator/Standby session fee (ZAR)' },
      { key: 'admin_day_hours', value: adminDayHoursInput || '9.5', description: 'Admin working hours per active day (shoots/standby)' },
    ];
    for (const pair of pairs) {
      const existing = appSettings.find(s => s.key === pair.key);
      if (existing) {
        await base44.entities.AppSettings.update(existing.id, { value: pair.value });
      } else {
        await base44.entities.AppSettings.create(pair);
      }
    }
    setRatesSaved(true);
    setTimeout(() => setRatesSaved(false), 2000);
    queryClient.invalidateQueries({ queryKey: ['appSettings'] });
  };

  const handleSaveSlackMessages = async () => {
    for (const phase of SLACK_PHASES) {
      if (slackMsgs[phase.key] !== undefined) {
        const existing = appSettings.find(s => s.key === `slack_${phase.key}`);
        if (existing) {
          await base44.entities.AppSettings.update(existing.id, { value: slackMsgs[phase.key] });
        } else {
          await base44.entities.AppSettings.create({ key: `slack_${phase.key}`, value: slackMsgs[phase.key] });
        }
      }
    }
    setSlackSaved(true);
    setTimeout(() => setSlackSaved(false), 2000);
    queryClient.invalidateQueries({ queryKey: ['appSettings'] });
  };

  const upsertSetting = async (key, value, description) => {
    const latest = await base44.entities.AppSettings.list();
    const matches = latest.filter((s) => s.key === key);
    const [keep, ...extras] = matches;
    if (keep) {
      await base44.entities.AppSettings.update(keep.id, { value });
      await Promise.all(extras.map((row) => base44.entities.AppSettings.delete(row.id)));
    } else {
      await base44.entities.AppSettings.create({ key, value, description });
    }
    await queryClient.invalidateQueries({ queryKey: ['appSettings'] });
  };

  const handleLogoUpload = async (e) => {
    const input = e.target;
    const file = input.files?.[0];
    if (!file) return;
    if (isHeicFile(file)) {
      setLogoError('iPhone HEIC photos are not supported. Export or screenshot as PNG or JPEG.');
      input.value = '';
      return;
    }
    if (!isAllowedLogoFile(file)) {
      setLogoError('Please upload a PNG, JPEG, WebP, GIF, SVG, or ICO image.');
      input.value = '';
      return;
    }
    setLogoError('');
    setLogoUploading(true);
    try {
      const { file_url } = await base44.integrations.Core.UploadFile({ file });
      if (!file_url) throw new Error('Upload did not return a file URL');
      await upsertSetting('app_logo_url', file_url, 'Custom app logo');
      await refreshPublicSettings();
    } catch (err) {
      setLogoError(err.message || 'Logo upload failed');
    } finally {
      setLogoUploading(false);
      input.value = '';
    }
  };

  const handleLoginBackgroundUpload = async (e) => {
    const input = e.target;
    const file = input.files?.[0];
    if (!file) return;
    if (isHeicFile(file)) {
      setBgError('iPhone HEIC photos are not supported. Export or screenshot as PNG or JPEG.');
      input.value = '';
      return;
    }
    if (!isAllowedLogoFile(file)) {
      setBgError('Please upload a PNG, JPEG, WebP, GIF, SVG, or ICO image.');
      input.value = '';
      return;
    }
    setBgError('');
    setBgUploading(true);
    try {
      const { file_url } = await base44.integrations.Core.UploadFile({ file });
      if (!file_url) throw new Error('Upload did not return a file URL');
      await upsertSetting('login_background_url', file_url, 'Sign-in page background image');
      await refreshPublicSettings();
    } catch (err) {
      setBgError(err.message || 'Background upload failed');
    } finally {
      setBgUploading(false);
      input.value = '';
    }
  };

  const handleClearLoginBackground = async () => {
    setBgError('');
    try {
      await upsertSetting('login_background_url', '', 'Sign-in page background image');
      await refreshPublicSettings();
    } catch (err) {
      setBgError(err.message || 'Could not remove the background image');
    }
  };

  const handleClearLogo = async () => {
    setLogoError('');
    try {
      await upsertSetting('app_logo_url', '', 'Custom app logo');
      await refreshPublicSettings();
    } catch (err) {
      setLogoError(err.message || 'Could not restore the default logo');
    }
  };

  const handleSplashUpload = async (e) => {
    const input = e.target;
    const file = input.files?.[0];
    if (!file) return;
    if (isHeicFile(file)) {
      setSplashError('iPhone HEIC photos are not supported. Export or screenshot as PNG or JPEG.');
      input.value = '';
      return;
    }
    if (!isAllowedLogoFile(file)) {
      setSplashError('Please upload a PNG, JPEG, WebP, GIF, SVG, or ICO image.');
      input.value = '';
      return;
    }
    setSplashError('');
    setSplashUploading(true);
    try {
      const { file_url } = await base44.integrations.Core.UploadFile({ file });
      if (!file_url) throw new Error('Upload did not return a file URL');
      await upsertSetting('splash_image_url', file_url, 'Loading screen image');
      await refreshPublicSettings();
    } catch (err) {
      setSplashError(err.message || 'Loading screen upload failed');
    } finally {
      setSplashUploading(false);
      input.value = '';
    }
  };

  const handleClearSplash = async () => {
    setSplashError('');
    try {
      await upsertSetting('splash_image_url', '', 'Loading screen image');
      await refreshPublicSettings();
    } catch (err) {
      setSplashError(err.message || 'Could not remove the loading screen image');
    }
  };

  const handleSaveTheme = async (theme) => {
    await upsertSetting('theme_canvas', theme.canvas, 'Page background colour');
    await upsertSetting('theme_surface', theme.surface, 'Dashboard card colour');
    await upsertSetting('theme_accent', theme.accent, 'Accent colour');
    await upsertSetting('theme_line', theme.line, 'Card border colour');
    await refreshPublicSettings();
  };

  return (
    <div className="min-h-screen bg-slate-800 text-slate-100 p-3 md:p-6 overflow-x-hidden">
      <div className="max-w-4xl mx-auto">
        <div className="flex items-center justify-between gap-3 mb-8 flex-wrap">
          <h1 className="text-2xl md:text-3xl font-bold">Settings</h1>
          <Button onClick={() => window.location.reload()} variant="outline" className="border-slate-800 text-slate-400 hover:bg-slate-800 gap-2">
            <RefreshCw className="h-4 w-4" /> Refresh App
          </Button>
        </div>

        {/* My Profile */}
        <Card className="bg-slate-900 border-slate-800 mb-6">
          <CardHeader className="border-b border-slate-800 pb-4">
            <CardTitle className="text-slate-100 flex items-center gap-2">
              <User className="h-5 w-5 text-orange-400" /> My Profile
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4">
            <div className="flex items-center gap-4 flex-wrap">
              <div className="w-14 h-14 bg-slate-800 rounded-full flex items-center justify-center text-2xl font-bold text-orange-400">
                {user?.full_name?.charAt(0) || user?.email?.charAt(0)?.toUpperCase() || 'U'}
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-lg font-semibold text-slate-100">{user?.full_name || 'Unnamed'}</p>
                <p className="text-slate-400 text-sm">{user?.email}</p>
                <Badge className={`mt-1 text-xs ${user?.role === 'admin' ? 'bg-orange-500/20 text-orange-400 border-orange-800' : user?.role === 'standby' ? 'bg-yellow-500/20 text-amber-400 border-yellow-500/30' : user?.role === 'analytics' ? 'bg-cyan-500/20 text-cyan-300 border-cyan-800' : user?.role === 'viewer' ? 'bg-slate-600/30 text-slate-300 border-slate-600' : 'bg-slate-700 text-slate-400 border-slate-700'}`}>
                {user?.role === 'admin' ? 'Admin' : user?.role === 'standby' ? 'Operator / Standby' : user?.role === 'accounts' ? 'Accounts' : user?.role === 'analytics' ? 'Data Analytics' : user?.role === 'viewer' ? 'Viewer' : 'Remote Operator'}
                </Badge>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-slate-900 border-slate-800 mb-6">
          <CardHeader className="border-b border-slate-800 pb-4">
            <CardTitle className="text-slate-100 flex items-center gap-2">
              <KeyRound className="h-5 w-5 text-orange-400" /> Change password
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4">
            <p className="text-xs text-slate-500 mb-4">
              Use this to replace a generated password, or whenever you want a new one.
            </p>
            <ChangePasswordCard />
          </CardContent>
        </Card>

        <Card className="bg-slate-900 border-slate-800 mb-6">
          <CardHeader className="border-b border-slate-800 pb-4">
            <CardTitle className="text-slate-100 flex items-center gap-2">
              <Globe className="h-5 w-5 text-orange-400" /> Time zone
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4 space-y-3">
            <p className="text-xs text-slate-500">
              Default is South African Time. After you set a time zone, the clock, calendar times, standby banner, and shoot times follow it.
            </p>
            <select
              value={storedTimezone || 'Africa/Johannesburg'}
              onChange={async (e) => {
                await setTimezone(e.target.value);
                setTimezoneSaved(true);
                setTimeout(() => setTimezoneSaved(false), 2000);
              }}
              className="w-full max-w-md rounded-md border border-slate-700 bg-slate-800 px-3 py-2 text-sm text-slate-100"
            >
              {TIMEZONE_OPTIONS.map((option) => (
                <option key={option.value} value={option.value}>{option.label}</option>
              ))}
            </select>
            <p className="text-sm text-slate-300">
              Now:{' '}
              <span className="font-mono tabular-nums">
                {now.toLocaleTimeString('en-ZA', { timeZone, hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false })}
              </span>
              <span className="text-slate-500"> {abbr}</span>
              {storedTimezone === 'device' && (
                <span className="text-slate-500"> · device {deviceTimeZone()} ({formatTimezoneAbbr(deviceTimeZone())})</span>
              )}
            </p>
            {timezoneSaved && <p className="text-xs text-emerald-400">Time zone saved. Times across the app now use this zone.</p>}
          </CardContent>
        </Card>

        {(isAccounts || isAdmin) && (
          <InvoiceExportNameCard appSettings={appSettings} queryClient={queryClient} />
        )}

        <Card className="bg-slate-900 border-slate-800 mb-6">
          <CardHeader className="border-b border-slate-800 pb-4">
            <CardTitle className="text-slate-100 flex items-center gap-2">
              <Bell className="h-5 w-5 text-orange-400" /> Device Notifications
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4">
            <EnablePushCard />
          </CardContent>
        </Card>

        {isAdmin && (
          <div className="mb-3 mt-2">
            <h2 className="text-sm font-semibold text-slate-300">Admin settings</h2>
            <p className="text-xs text-slate-500 mt-0.5">Grouped by topic and collapsed by default. Open a section to change it.</p>
          </div>
        )}

        {isAdmin && (
          <SettingsCategory
            title="Calendar"
            description="Google Data + Fancam sync. Slack Gameday is a fail-safe. Auto-syncs at 06:00, 13:00 and 20:00 SAST."
            icon={CalendarDays}
          >
            <GoogleCalendarSettings />
            <SlackGamesSettings canEdit />
          </SettingsCategory>
        )}

        {isAnalytics && (
          <SettingsCategory
            title="Calendar sync"
            description="Pull Google or the Gameday Slack channel the same way admins do. Paste is a fail-safe."
            icon={CalendarDays}
            defaultOpen
          >
            <AnalyticsGoogleSync />
            <SlackGamesSettings canEdit={false} />
          </SettingsCategory>
        )}

        {isAdmin && (
          <SettingsCategory
            title="Data import"
            description="Bring in Base44 CSV or JSON exports"
            icon={Database}
          >
            <DataImportSection />
          </SettingsCategory>
        )}

        {isAdmin && (
          <SettingsCategory
            title="Pay rates"
            description="Standard, additional, postponed, standby, and admin hours"
            icon={DollarSign}
          >
            <Card className="bg-slate-900 border-slate-800">
              <CardHeader className="border-b border-slate-800 pb-4">
                <CardTitle className="text-slate-100 flex items-center gap-2">
                  <DollarSign className="h-5 w-5 text-emerald-400" /> Pay Rates (ZAR)
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-4 space-y-4">
                <p className="text-xs text-slate-500">Additional shoots only apply when within 2 hours of a standard shoot on the same day. Cancelled shoots show as Cancelled with no pay. Postponed shoots pay the postponed fee. Operator / Standby users earn the standby session fee for each 18:00–06:00 coverage night.</p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="text-xs text-slate-400 block mb-1">Standard Shoot Rate (R)</label>
                    <Input
                      type="number"
                      value={rateBaseInput}
                      onChange={e => setRateBaseInput(e.target.value)}
                      placeholder="1000"
                      className="bg-slate-800 border-slate-800 text-slate-100"
                    />
                  </div>
                  <div>
                    <label className="text-xs text-slate-400 block mb-1">Additional Shoot Rate (R)</label>
                    <Input
                      type="number"
                      value={rateAdditionalInput}
                      onChange={e => setRateAdditionalInput(e.target.value)}
                      placeholder="250"
                      className="bg-slate-800 border-slate-800 text-slate-100"
                    />
                  </div>
                  <div>
                    <label className="text-xs text-slate-400 block mb-1">Postponed Shoot Fee (R)</label>
                    <Input
                      type="number"
                      value={ratePostponedInput}
                      onChange={e => setRatePostponedInput(e.target.value)}
                      placeholder="250"
                      className="bg-slate-800 border-slate-800 text-slate-100"
                    />
                  </div>
                  <div>
                    <label className="text-xs text-slate-400 block mb-1">Operator / Standby Session (R)</label>
                    <Input
                      type="number"
                      value={rateStandbyInput}
                      onChange={e => setRateStandbyInput(e.target.value)}
                      placeholder="500"
                      className="bg-slate-800 border-slate-800 text-slate-100"
                    />
                    <p className="text-xs text-gray-600 mt-1">One 18:00–06:00 standby session</p>
                  </div>
                  <div>
                    <label className="text-xs text-slate-400 block mb-1">Admin Working Hours / Active Day</label>
                    <Input
                      type="number"
                      step="0.5"
                      value={adminDayHoursInput}
                      onChange={e => setAdminDayHoursInput(e.target.value)}
                      placeholder="9.5"
                      className="bg-slate-800 border-slate-800 text-slate-100"
                    />
                    <p className="text-xs text-gray-600 mt-1">Hours counted per day with a shoot or standby (never doubled)</p>
                  </div>
                </div>
                <Button onClick={handleSaveRates} className="bg-green-700 hover:bg-green-600 gap-2">
                  <Save className="h-4 w-4" /> {ratesSaved ? '✓ Saved!' : 'Save Rates'}
                </Button>
              </CardContent>
            </Card>
          </SettingsCategory>
        )}

        {isAdmin && (
          <SettingsCategory
            title="Rig checks"
            description="Who can tick calendar rig checks, and which Slack group gets the ready message"
            icon={MessageSquare}
          >
            <RigCheckUsersSettings appSettings={appSettings} allUsers={allUsers} />
            <RigCheckSlackSettings />
          </SettingsCategory>
        )}

        {isAdmin && (
          <SettingsCategory
            title="Messages"
            description="Rigs check, shoot summary, and phase Slack copy"
            icon={MessageSquare}
          >
            <MessageTemplatesSection appSettings={appSettings} queryClient={queryClient} />
            <Card className="bg-slate-900 border-slate-800">
              <CardHeader className="border-b border-slate-800 pb-4">
                <CardTitle className="text-slate-100 flex items-center gap-2">
                  <MessageSquare className="h-5 w-5 text-emerald-400" /> Phase Slack Messages
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-4 space-y-3">
                <p className="text-xs text-slate-500">Use <code className="text-orange-400">{'{team}'}</code> to insert the team/client name dynamically.</p>
                {SLACK_PHASES.map(phase => (
                  <div key={phase.key}>
                    <label className="text-xs text-slate-400 block mb-1">{phase.label}</label>
                    <Input
                      placeholder={phase.placeholder}
                      value={slackMsgs[phase.key] || ''}
                      onChange={e => setSlackMsgs({ ...slackMsgs, [phase.key]: e.target.value })}
                      className="bg-slate-800 border-slate-800 text-slate-100 placeholder:text-gray-600 text-sm"
                    />
                  </div>
                ))}
                <Button onClick={handleSaveSlackMessages} className="bg-green-700 hover:bg-green-600 gap-2">
                  <Save className="h-4 w-4" /> {slackSaved ? '✓ Saved!' : 'Save Messages'}
                </Button>
              </CardContent>
            </Card>
          </SettingsCategory>
        )}

        {isAdmin && (
          <SettingsCategory
            title="Team"
            description="Users, roles, password reset, who can assign to which games, and auto-assignment"
            icon={Users}
          >
            <ManageUsersSection queryClient={queryClient} />
            <RestrictedAssignSettings appSettings={appSettings} />
            <AutoAssignSettings appSettings={appSettings} allUsers={allUsers} />
          </SettingsCategory>
        )}

        {isAdmin && (
          <SettingsCategory
            title="Appearance"
            description="App icon, loading screen, colours, and sign-in background"
            icon={Image}
            defaultOpen
          >
            <Card className="bg-slate-900 border-slate-800">
              <CardHeader className="border-b border-slate-800 pb-4">
                <CardTitle className="text-slate-100 flex items-center gap-2">
                  <Image className="h-5 w-5 text-orange-400" /> App icon
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-4">
                <AppLogoControls
                  logoUrl={logoUrl}
                  uploading={logoUploading}
                  error={logoError}
                  onUpload={handleLogoUpload}
                  onClear={handleClearLogo}
                />
              </CardContent>
            </Card>
            <Card className="bg-slate-900 border-slate-800 mt-4">
              <CardHeader className="border-b border-slate-800 pb-4">
                <CardTitle className="text-slate-100 flex items-center gap-2">
                  <Image className="h-5 w-5 text-orange-400" /> Loading screen
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-4">
                <div className="flex items-start gap-4 flex-wrap">
                  <div className="w-28 h-28 bg-slate-800 rounded-xl overflow-hidden border border-slate-800 flex items-center justify-center">
                    <img
                      src={resolveAppLogoUrl(splashUrl || logoUrl)}
                      alt="Loading screen"
                      className="max-h-full max-w-full object-contain"
                    />
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-sm text-slate-400 mb-2">
                      Shown on the charcoal load screen. This can be a different image from the app icon. PNG, JPEG, WebP, GIF, SVG, or ICO.
                    </p>
                    <div className="flex flex-wrap gap-2">
                      <FilePickerButton
                        id="splash-image-file"
                        accept={`image/*,${APP_LOGO_ACCEPT}`}
                        disabled={splashUploading}
                        onChange={handleSplashUpload}
                      >
                        <Image className="h-4 w-4" />
                        {splashUploading ? 'Uploading...' : splashUrl ? 'Replace image' : 'Upload image'}
                      </FilePickerButton>
                      {splashUrl && (
                        <Button type="button" size="sm" variant="outline" onClick={handleClearSplash}
                          className="border-slate-700 text-slate-300 hover:bg-slate-800">
                          Use app icon
                        </Button>
                      )}
                    </div>
                    {splashError ? <p className="text-xs text-red-400 mt-2">{splashError}</p> : null}
                  </div>
                </div>
              </CardContent>
            </Card>
            <AppearanceThemeControls
              appSettings={appSettings}
              logoUrl={logoUrl}
              splashUrl={splashUrl}
              onSave={handleSaveTheme}
            />
            <Card className="bg-slate-900 border-slate-800 mt-4">
              <CardHeader className="border-b border-slate-800 pb-4">
                <CardTitle className="text-slate-100 flex items-center gap-2">
                  <Image className="h-5 w-5 text-orange-400" /> Sign-in background
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-4">
                <div className="flex items-start gap-4 flex-wrap">
                  <div className="w-40 h-24 bg-slate-800 rounded-xl overflow-hidden border border-slate-800 bg-cover bg-center"
                    style={loginBgUrl ? { backgroundImage: `url("${loginBgUrl}")` } : undefined}>
                    {!loginBgUrl && <div className="h-full w-full flex items-center justify-center text-xs text-slate-500">No image</div>}
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-sm text-slate-400 mb-2">
                      Shown behind the sign-in and create-account screens. A dark overlay keeps the form readable. Wide photos work best.
                    </p>
                    <div className="flex flex-wrap gap-2">
                      <FilePickerButton
                        id="login-bg-file"
                        accept={`image/*,${APP_LOGO_ACCEPT}`}
                        disabled={bgUploading}
                        onChange={handleLoginBackgroundUpload}
                      >
                        <Image className="h-4 w-4" />
                        {bgUploading ? 'Uploading...' : loginBgUrl ? 'Replace image' : 'Upload image'}
                      </FilePickerButton>
                      {loginBgUrl && (
                        <Button type="button" size="sm" variant="outline" onClick={handleClearLoginBackground}
                          className="border-slate-700 text-slate-300 hover:bg-slate-800">
                          Remove
                        </Button>
                      )}
                    </div>
                    {bgError ? <p className="text-xs text-red-400 mt-2">{bgError}</p> : null}
                  </div>
                </div>
              </CardContent>
            </Card>
          </SettingsCategory>
        )}

        {isAdmin && (
          <SettingsCategory
            title="App updates"
            description="Remind the team to refresh after a server update"
            icon={RefreshCw}
          >
            <Card className="bg-slate-900 border-slate-800">
              <CardHeader className="border-b border-slate-800 pb-4">
                <CardTitle className="text-slate-100 flex items-center gap-2">
                  <RefreshCw className="h-5 w-5 text-orange-400" /> App Updates
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-4">
                <p className="text-xs text-slate-500 mb-1">After you ship an update on the server, use this to remind everyone to refresh their browser.</p>
                <AppVersionBump appSettings={appSettings} queryClient={queryClient} />
              </CardContent>
            </Card>
          </SettingsCategory>
        )}


      </div>
    </div>
  );
}