import React, { useState, useEffect, useRef, useMemo } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { useApp } from '../components/AppContext';
import ManageUsersSection from '../components/settings/ManageUsersSection';
import AutoAssignSettings from '../components/settings/AutoAssignSettings';
import GoogleCalendarSettings from '../components/settings/GoogleCalendarSettings';
import EnablePushCard from '../components/notifications/EnablePushCard';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import {
  User, RefreshCw, MessageSquare, Save, Image, DollarSign, Bell
} from 'lucide-react';

function MessageTemplatesSection({ appSettings, queryClient }) {
  const defaultRigs = 'Rigs ready for today: {list}';
  const defaultOk = '{name} complete, no issues to report.';
  const defaultIssues = '{name} complete — ⚠️ Issues reported: {notes}';

  const [rigsTemplate, setRigsTemplate] = React.useState('');
  const [summaryOk, setSummaryOk] = React.useState('');
  const [summaryIssues, setSummaryIssues] = React.useState('');
  const [saved, setSaved] = React.useState(false);

  React.useEffect(() => {
    if (!appSettings.length) return;
    setRigsTemplate(appSettings.find(s => s.key === 'rigscheck_template')?.value || defaultRigs);
    setSummaryOk(appSettings.find(s => s.key === 'summary_template_ok')?.value || defaultOk);
    setSummaryIssues(appSettings.find(s => s.key === 'summary_template_issues')?.value || defaultIssues);
  }, [appSettings]);

  const handleSave = async () => {
    const pairs = [
      { key: 'rigscheck_template', value: rigsTemplate, description: 'Rigs check message template' },
      { key: 'summary_template_ok', value: summaryOk, description: 'Shoot summary — no issues template' },
      { key: 'summary_template_issues', value: summaryIssues, description: 'Shoot summary — issues template' },
    ];
    for (const pair of pairs) {
      const existing = appSettings.find(s => s.key === pair.key);
      if (existing) {
        await base44.entities.AppSettings.update(existing.id, { value: pair.value });
      } else {
        await base44.entities.AppSettings.create(pair);
      }
    }
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
    queryClient.invalidateQueries({ queryKey: ['appSettings'] });
  };

  return (
    <Card className="bg-slate-900 border-slate-800 mb-6">
      <CardHeader className="border-b border-slate-800 pb-4">
        <CardTitle className="text-slate-100 flex items-center gap-2">
          <MessageSquare className="h-5 w-5 text-blue-400" /> Message Templates
        </CardTitle>
      </CardHeader>
      <CardContent className="pt-4 space-y-4">
        <p className="text-xs text-slate-500">
          Customise the messages generated by the Rigs Check and Shoot Summary panels.
        </p>

        <div>
          <label className="text-xs text-slate-400 block mb-1">
            Rigs Check message — use <code className="text-blue-400">{'{list}'}</code> for the shoot list
          </label>
          <Input
            value={rigsTemplate}
            onChange={e => setRigsTemplate(e.target.value)}
            placeholder={defaultRigs}
            className="bg-slate-800 border-slate-800 text-slate-100 placeholder:text-gray-600 text-sm"
          />
          <p className="text-xs text-gray-600 mt-1">
            Example output: <span className="text-slate-400 italic">Rigs ready for today: Nationals (Data/Fancam), Lightning (Data/Fancam/Sound)</span>
          </p>
        </div>

        <div>
          <label className="text-xs text-slate-400 block mb-1">
            Shoot Summary — no issues — use <code className="text-blue-400">{'{name}'}</code> for shoot name
          </label>
          <Input
            value={summaryOk}
            onChange={e => setSummaryOk(e.target.value)}
            placeholder={defaultOk}
            className="bg-slate-800 border-slate-800 text-slate-100 placeholder:text-gray-600 text-sm"
          />
        </div>

        <div>
          <label className="text-xs text-slate-400 block mb-1">
            Shoot Summary — issues reported — use <code className="text-blue-400">{'{name}'}</code> and <code className="text-blue-400">{'{notes}'}</code>
          </label>
          <Input
            value={summaryIssues}
            onChange={e => setSummaryIssues(e.target.value)}
            placeholder={defaultIssues}
            className="bg-slate-800 border-slate-800 text-slate-100 placeholder:text-gray-600 text-sm"
          />
        </div>

        <Button onClick={handleSave} className="bg-blue-600 hover:bg-blue-600 gap-2">
          <Save className="h-4 w-4" /> {saved ? '✓ Saved!' : 'Save Templates'}
        </Button>
      </CardContent>
    </Card>
  );
}



// App Version bump — triggers RefreshReminder for all users
function AppVersionBump({ appSettings, queryClient }) {
  const [bumping, setBumping] = React.useState(false);
  const [done, setDone] = React.useState(false);

  const handleBump = async () => {
    setBumping(true);
    const newVersion = Date.now().toString();
    const existing = appSettings.find(s => s.key === 'app_version');
    if (existing) {
      await base44.entities.AppSettings.update(existing.id, { value: newVersion });
    } else {
      await base44.entities.AppSettings.create({ key: 'app_version', value: newVersion, description: 'App version — bump to notify users to refresh' });
    }
    setBumping(false);
    setDone(true);
    setTimeout(() => setDone(false), 3000);
    queryClient.invalidateQueries({ queryKey: ['appSettings'] });
  };

  return (
    <div className="border-t border-slate-800 pt-4 mt-2">
      <p className="text-xs text-slate-500 mb-2">Notify all users to refresh the app (e.g. after a major update):</p>
      <Button size="sm" onClick={handleBump} disabled={bumping}
        className="bg-orange-700 hover:bg-orange-600 gap-2 text-sm">
        <RefreshCw className="h-4 w-4" />
        {done ? '✓ Notification sent!' : bumping ? 'Sending...' : 'Send Refresh Reminder to All Users'}
      </Button>
    </div>
  );
}

const SLACK_PHASES = [
  { key: 'setup_complete', label: 'Setup Complete', placeholder: 'Setup complete — {team} shoot ready to go!' },
  { key: 'pre_shoot_started', label: 'Pre-Shoot Started', placeholder: 'Pre-shoot started — {team}' },
  { key: 'attention_started', label: 'Attention Started', placeholder: 'Attention phase started — {team}' },
  { key: 'sound_started', label: 'Sound Started', placeholder: 'Sound check in progress — {team}' },
];

export default function Settings() {
  const { user, isAdmin } = useApp();
  const queryClient = useQueryClient();

  const [slackMsgs, setSlackMsgs] = useState({});
  const [slackSaved, setSlackSaved] = useState(false);
  const [rateBaseInput, setRateBaseInput] = useState('');
  const [adminDayHoursInput, setAdminDayHoursInput] = useState('9.5');
  const [rateAdditionalInput, setRateAdditionalInput] = useState('');
  const [ratePostponedInput, setRatePostponedInput] = useState('250');
  const [ratesSaved, setRatesSaved] = useState(false);

  // Logo
  const [logoUploading, setLogoUploading] = useState(false);
  const logoInputRef = useRef();

  const { data: appSettings = [] } = useQuery({
    queryKey: ['appSettings'],
    queryFn: () => base44.entities.AppSettings.list(),
  });

  const { data: rawUsers = [] } = useQuery({
    queryKey: ['allUsers'],
    queryFn: () => base44.entities.User.list(),
    enabled: isAdmin,
  });

  const { data: pendingUsers = [] } = useQuery({
    queryKey: ['pendingUsers'],
    queryFn: () => base44.entities.PendingUser.list(),
    enabled: isAdmin,
  });

  // Merge PendingUser (admin-defined names/roles) with User entity records
  const allUsers = useMemo(() => {
    const map = new Map();
    pendingUsers.forEach(pu => {
      const email = pu.email?.trim().toLowerCase();
      if (!email) return;
      map.set(email, { email, full_name: pu.full_name || '', role: pu.role || 'user', inactive: pu.inactive || false });
    });
    rawUsers.forEach(u => {
      const email = u.email?.trim().toLowerCase();
      if (!email) return;
      const existing = map.get(email);
      // Use PendingUser role only if it's a non-empty string; otherwise fall back to User entity role
      const resolvedRole = (existing?.role && existing.role !== '') ? existing.role : (u.role || 'user');
      map.set(email, { ...u, email, full_name: existing?.full_name || u.full_name || '', role: resolvedRole, inactive: existing?.inactive || false });
    });
    return Array.from(map.values());
  }, [rawUsers, pendingUsers]);



  const logoSetting = appSettings.find(s => s.key === 'app_logo_url');
  const logoUrl = logoSetting?.value;

  useEffect(() => {
    if (!appSettings.length) return;
    const msgs = {};
    SLACK_PHASES.forEach(p => {
      const setting = appSettings.find(s => s.key === `slack_${p.key}`);
      if (setting) msgs[p.key] = setting.value;
    });
    setSlackMsgs(msgs);
    const br = appSettings.find(s => s.key === 'base_rate')?.value;
    const ar = appSettings.find(s => s.key === 'additional_rate')?.value;
    const pr = appSettings.find(s => s.key === 'postponed_rate')?.value;
    if (br) setRateBaseInput(br);
    if (ar) setRateAdditionalInput(ar);
    if (pr) setRatePostponedInput(pr);
    const adh = appSettings.find(s => s.key === 'admin_day_hours')?.value;
    if (adh) setAdminDayHoursInput(adh);
  }, [appSettings]);

  const handleSaveRates = async () => {
    const pairs = [
      { key: 'base_rate', value: rateBaseInput || '1000', description: 'Standard shoot rate (ZAR)' },
      { key: 'additional_rate', value: rateAdditionalInput || '250', description: 'Additional shoot rate (ZAR)' },
      { key: 'postponed_rate', value: ratePostponedInput || '250', description: 'Postponed shoot fee (ZAR)' },
      { key: 'admin_day_hours', value: adminDayHoursInput || '9.5', description: 'Admin working hours per active day (shoots/standby)' },
    ];
    for (const pair of pairs) {
      const existing = appSettings.find(s => s.key === pair.key);
      if (existing) {
        await base44.entities.AppSettings.update(existing.id, { value: pair.value });
      } else {
        await base44.entities.AppSettings.create(pair);
      }
    }
    setRatesSaved(true);
    setTimeout(() => setRatesSaved(false), 2000);
    queryClient.invalidateQueries({ queryKey: ['appSettings'] });
  };

  const handleSaveSlackMessages = async () => {
    for (const phase of SLACK_PHASES) {
      if (slackMsgs[phase.key] !== undefined) {
        const existing = appSettings.find(s => s.key === `slack_${phase.key}`);
        if (existing) {
          await base44.entities.AppSettings.update(existing.id, { value: slackMsgs[phase.key] });
        } else {
          await base44.entities.AppSettings.create({ key: `slack_${phase.key}`, value: slackMsgs[phase.key] });
        }
      }
    }
    setSlackSaved(true);
    setTimeout(() => setSlackSaved(false), 2000);
    queryClient.invalidateQueries({ queryKey: ['appSettings'] });
  };

  const handleLogoUpload = async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setLogoUploading(true);
    const { file_url } = await base44.integrations.Core.UploadFile({ file });
    if (logoSetting) {
      await base44.entities.AppSettings.update(logoSetting.id, { value: file_url });
    } else {
      await base44.entities.AppSettings.create({ key: 'app_logo_url', value: file_url, description: 'Custom app logo' });
    }
    setLogoUploading(false);
    queryClient.invalidateQueries({ queryKey: ['appSettings'] });
  };

  return (
    <div className="min-h-screen bg-slate-800 text-slate-100 p-4 md:p-6">
      <div className="max-w-4xl mx-auto">
        <div className="flex items-center justify-between mb-8">
          <h1 className="text-3xl font-bold">Settings</h1>
          <Button onClick={() => window.location.reload()} variant="outline" className="border-slate-800 text-slate-400 hover:bg-slate-800 gap-2">
            <RefreshCw className="h-4 w-4" /> Refresh App
          </Button>
        </div>

        {/* My Profile */}
        <Card className="bg-slate-900 border-slate-800 mb-6">
          <CardHeader className="border-b border-slate-800 pb-4">
            <CardTitle className="text-slate-100 flex items-center gap-2">
              <User className="h-5 w-5 text-blue-400" /> My Profile
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4">
            <div className="flex items-center gap-4 flex-wrap">
              <div className="w-14 h-14 bg-slate-800 rounded-full flex items-center justify-center text-2xl font-bold text-blue-400">
                {user?.full_name?.charAt(0) || user?.email?.charAt(0)?.toUpperCase() || 'U'}
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-lg font-semibold text-slate-100">{user?.full_name || 'Unnamed'}</p>
                <p className="text-slate-400 text-sm">{user?.email}</p>
                <Badge className={`mt-1 text-xs ${user?.role === 'admin' ? 'bg-blue-600/20 text-blue-400 border-blue-800' : user?.role === 'standby' ? 'bg-yellow-500/20 text-amber-400 border-yellow-500/30' : 'bg-slate-700 text-slate-400 border-slate-700'}`}>
                {user?.role === 'admin' ? 'Admin' : user?.role === 'standby' ? 'Standby User' : 'Remote Operator'}
                </Badge>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* App Logo — Admin only */}
        {isAdmin && (
          <Card className="bg-slate-900 border-slate-800 mb-6">
            <CardHeader className="border-b border-slate-800 pb-4">
              <CardTitle className="text-slate-100 flex items-center gap-2">
                <Image className="h-5 w-5 text-blue-400" /> App Logo
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-4">
              <div className="flex items-center gap-4 flex-wrap">
                <div className="w-16 h-16 bg-slate-800 rounded-xl flex items-center justify-center overflow-hidden border border-slate-800">
                  {logoUrl
                    ? <img src={logoUrl} alt="App Logo" className="w-full h-full object-contain" />
                    : <span className="text-2xl font-bold text-blue-400">R</span>
                  }
                </div>
                <div>
                  <p className="text-sm text-slate-400 mb-2">Upload a custom logo (PNG, JPG, SVG recommended)</p>
                  <input ref={logoInputRef} type="file" accept="image/*" className="hidden" onChange={handleLogoUpload} />
                  <Button size="sm" onClick={() => logoInputRef.current?.click()} disabled={logoUploading}
                    className="bg-blue-600 hover:bg-blue-600 gap-2">
                    <Image className="h-4 w-4" />
                    {logoUploading ? 'Uploading...' : 'Upload Logo'}
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Push / install — all roles */}
        <Card className="bg-slate-900 border-slate-800 mb-6">
          <CardHeader className="border-b border-slate-800 pb-4">
            <CardTitle className="text-slate-100 flex items-center gap-2">
              <Bell className="h-5 w-5 text-blue-400" /> Device Notifications
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4">
            <EnablePushCard />
          </CardContent>
        </Card>

        {isAdmin && <GoogleCalendarSettings />}

        {/* Pay Rates — Admin only */}
        {isAdmin && (
          <Card className="bg-slate-900 border-slate-800 mb-6">
            <CardHeader className="border-b border-slate-800 pb-4">
              <CardTitle className="text-slate-100 flex items-center gap-2">
                <DollarSign className="h-5 w-5 text-emerald-400" /> Pay Rates (ZAR)
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-4 space-y-4">
              <p className="text-xs text-slate-500">Additional shoots only apply when within 2 hours of a standard shoot on the same day. Cancelled shoots show as Cancelled with no pay. Postponed shoots pay the postponed fee.</p>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="text-xs text-slate-400 block mb-1">Standard Shoot Rate (R)</label>
                  <Input
                    type="number"
                    value={rateBaseInput}
                    onChange={e => setRateBaseInput(e.target.value)}
                    placeholder="1000"
                    className="bg-slate-800 border-slate-800 text-slate-100"
                  />
                </div>
                <div>
                  <label className="text-xs text-slate-400 block mb-1">Additional Shoot Rate (R)</label>
                  <Input
                    type="number"
                    value={rateAdditionalInput}
                    onChange={e => setRateAdditionalInput(e.target.value)}
                    placeholder="250"
                    className="bg-slate-800 border-slate-800 text-slate-100"
                  />
                </div>
                <div>
                  <label className="text-xs text-slate-400 block mb-1">Postponed Shoot Fee (R)</label>
                  <Input
                    type="number"
                    value={ratePostponedInput}
                    onChange={e => setRatePostponedInput(e.target.value)}
                    placeholder="250"
                    className="bg-slate-800 border-slate-800 text-slate-100"
                  />
                </div>
                <div>
                  <label className="text-xs text-slate-400 block mb-1">Admin Working Hours / Active Day</label>
                  <Input
                    type="number"
                    step="0.5"
                    value={adminDayHoursInput}
                    onChange={e => setAdminDayHoursInput(e.target.value)}
                    placeholder="9.5"
                    className="bg-slate-800 border-slate-800 text-slate-100"
                  />
                  <p className="text-xs text-gray-600 mt-1">Hours counted per day with a shoot or standby (never doubled)</p>
                </div>
              </div>
              <Button onClick={handleSaveRates} className="bg-green-700 hover:bg-green-600 gap-2">
                <Save className="h-4 w-4" /> {ratesSaved ? '✓ Saved!' : 'Save Rates'}
              </Button>
            </CardContent>
          </Card>
        )}

        {/* Message Templates — Admin only */}
        {isAdmin && (
          <MessageTemplatesSection appSettings={appSettings} queryClient={queryClient} />
        )}

        {/* App Version / Refresh Reminder — Admin only */}
        {isAdmin && (
          <Card className="bg-slate-900 border-slate-800 mb-6">
            <CardHeader className="border-b border-slate-800 pb-4">
              <CardTitle className="text-slate-100 flex items-center gap-2">
                <RefreshCw className="h-5 w-5 text-orange-400" /> App Updates
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-4">
              <p className="text-xs text-slate-500 mb-1">Use this after deploying changes to remind all logged-in users to refresh their browser.</p>
              <AppVersionBump appSettings={appSettings} queryClient={queryClient} />
            </CardContent>
          </Card>
        )}

        {/* Slack Messages — Admin only */}
        {isAdmin && (
          <Card className="bg-slate-900 border-slate-800 mb-6">
            <CardHeader className="border-b border-slate-800 pb-4">
              <CardTitle className="text-slate-100 flex items-center gap-2">
                <MessageSquare className="h-5 w-5 text-emerald-400" /> Phase Slack Messages
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-4 space-y-3">
              <p className="text-xs text-slate-500">Use <code className="text-blue-400">{'{team}'}</code> to insert the team/client name dynamically.</p>
              {SLACK_PHASES.map(phase => (
                <div key={phase.key}>
                  <label className="text-xs text-slate-400 block mb-1">{phase.label}</label>
                  <Input
                    placeholder={phase.placeholder}
                    value={slackMsgs[phase.key] || ''}
                    onChange={e => setSlackMsgs({ ...slackMsgs, [phase.key]: e.target.value })}
                    className="bg-slate-800 border-slate-800 text-slate-100 placeholder:text-gray-600 text-sm"
                  />
                </div>
              ))}
              <Button onClick={handleSaveSlackMessages} className="bg-green-700 hover:bg-green-600 gap-2">
                <Save className="h-4 w-4" /> {slackSaved ? '✓ Saved!' : 'Save Messages'}
              </Button>
            </CardContent>
          </Card>
        )}

        {/* Auto-Assignment Rules — Admin only */}
        {isAdmin && (
          <AutoAssignSettings appSettings={appSettings} allUsers={allUsers} />
        )}

        {/* Add / Manage Users — all admins */}
        {isAdmin && (
          <ManageUsersSection queryClient={queryClient} />
        )}


      </div>
    </div>
  );
}